// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXUKnGUFUufdAkp_CnsPIYKNEyZVfsi2k',
    appId: '1:877338330199:web:81689e893d8641981a0f12',
    messagingSenderId: '877338330199',
    projectId: 'sisabox-44bce',
    authDomain: 'sisabox-44bce.firebaseapp.com',
    storageBucket: 'sisabox-44bce.firebasestorage.app',
    measurementId: 'G-S3N9MWQCC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr3JbGRXIoGDMyLX6i2mOXzNc3TsdupqE',
    appId: '1:877338330199:android:3d8d59db7a848a981a0f12',
    messagingSenderId: '877338330199',
    projectId: 'sisabox-44bce',
    storageBucket: 'sisabox-44bce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI-mCCPWC-lb6m8Bnbu9eORfif-UbB8SY',
    appId: '1:877338330199:ios:9c75b04dbff6dd3a1a0f12',
    messagingSenderId: '877338330199',
    projectId: 'sisabox-44bce',
    storageBucket: 'sisabox-44bce.firebasestorage.app',
    iosClientId: '877338330199-f30rtsncasqkp2rmo6c34l496agk8j72.apps.googleusercontent.com',
    iosBundleId: 'com.example.sisabox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI-mCCPWC-lb6m8Bnbu9eORfif-UbB8SY',
    appId: '1:877338330199:ios:9c75b04dbff6dd3a1a0f12',
    messagingSenderId: '877338330199',
    projectId: 'sisabox-44bce',
    // storageBucket: 'sisabox-44bce.firebasestorage.app',
    storageBucket: 'sisabox-44bce.appspot.com',
    iosClientId: '877338330199-f30rtsncasqkp2rmo6c34l496agk8j72.apps.googleusercontent.com',
    iosBundleId: 'com.example.sisabox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXUKnGUFUufdAkp_CnsPIYKNEyZVfsi2k',
    appId: '1:877338330199:web:203edadd41bbb7ca1a0f12',
    messagingSenderId: '877338330199',
    projectId: 'sisabox-44bce',
    authDomain: 'sisabox-44bce.firebaseapp.com',
    storageBucket: 'sisabox-44bce.firebasestorage.app',
    measurementId: 'G-QWB6K825ND',
  );
}
